import type {
  AssistantResponse,
  BusinessImpact,
  EvidenceRecord,
  GraphEdge,
  GraphNode,
  Incident,
  IncidentEvent,
  Recommendation,
  ReplayStage,
  SimulationResult,
  WasteBreakdownItem,
  AnomalySummary,
} from './types';

const incidentDate = '2026-08-24';
const at = (time: string) => `${incidentDate}T${time}:00Z`;

export const incidents: Incident[] = [
  {
    id: 'INC-ENG-2401',
    title: 'Compressed-air distribution leakage & SEC surge',
    plant: 'Foundry Cluster - Belgaum',
    line: 'Induction Melting & Moulding Line 2',
    product: 'Ductile Iron Valve Bodies (Grade 400/18)',
    batchId: 'BATCH-FD-2408',
    severity: 'high',
    status: 'investigating',
    detectedAt: at('08:30'),
    baselineYield: 97.6,
    currentYield: 97.6,
    exposureInr: 187200,
    summary: 'SEC rose 14.3% in the last 6 hours (9.8 to 11.2 kWh/ton) due to Line 2 compressed-air leakage, triggering compressor overcycling while production throughput and quality remained completely stable.',
    baselineSec: 9.8,
    currentSec: 11.2,
    secUnit: 'kWh/ton',
    secDeltaPct: 14.3,
    dailyEnergyKwh: 8500,
    dailyCostInr: 68000,
    co2EmissionsTons: 0.90,
    airPressureBar: 6.1,
    compressorRuntimePct: 88,
    motorCurrentA: 142,
  },
  {
    id: 'INC-ENG-2402',
    title: 'Induction Furnace F-1 preheat idling excursion',
    plant: 'Forging Cluster - Pune',
    line: 'Billet Induction Heating Line 1',
    product: 'Forged Crankshaft Preforms',
    batchId: 'BATCH-FG-1102',
    severity: 'medium',
    status: 'monitoring',
    detectedAt: at('09:15'),
    baselineYield: 98.2,
    currentYield: 98.0,
    exposureInr: 85000,
    summary: 'Furnace F-1 preheat hold-fire idling sustained at 75 kW during extended tooling changeover, creating 180 kWh parasitic thermal loss.',
    baselineSec: 420,
    currentSec: 462,
    secUnit: 'kWh/ton',
    secDeltaPct: 10.0,
    dailyEnergyKwh: 12400,
    dailyCostInr: 96720,
    co2EmissionsTons: 1.32,
  },
  {
    id: 'INC-ENG-2403',
    title: 'Chiller CH-3 low power factor & reactive surcharge',
    plant: 'Textile Finishing - Surat',
    line: 'Yarn Dyeing Process Chiller',
    product: 'Polyester Micro-filament',
    batchId: 'BATCH-TX-089',
    severity: 'low',
    status: 'open',
    detectedAt: at('10:05'),
    baselineYield: 99.1,
    currentYield: 99.1,
    exposureInr: 45000,
    summary: 'Capacitor bank step 3 contactor weld failure dropped power factor to 0.81, causing reactive power draw and utility billing penalties.',
    baselineSec: 2.1,
    currentSec: 2.3,
    secUnit: 'kWh/kg',
    secDeltaPct: 9.5,
    dailyEnergyKwh: 5600,
    dailyCostInr: 44800,
    co2EmissionsTons: 0.58,
  },
  {
    id: 'INC-ENG-2404',
    title: 'Sand Muller hydraulic pump vane wear & friction draw',
    plant: 'Foundry Cluster - Coimbatore',
    line: 'Green Sand Preparation Plant',
    product: 'Automotive Brake Disc Moulds',
    batchId: 'BATCH-CB-401',
    severity: 'low',
    status: 'monitoring',
    detectedAt: at('11:20'),
    baselineYield: 96.5,
    currentYield: 96.4,
    exposureInr: 32000,
    summary: 'Muller hydraulic pump idle current increased by 14% above baseline; oil analysis confirms cavitation and internal bypass recirculation.',
    baselineSec: 3.4,
    currentSec: 3.65,
    secUnit: 'kWh/ton',
    secDeltaPct: 7.3,
    dailyEnergyKwh: 3800,
    dailyCostInr: 30400,
    co2EmissionsTons: 0.41,
  },
];

export const featuredIncident = incidents[0];

export const incidentEvents: IncidentEvent[] = [
  {
    id: 'evt_eng_01',
    timestamp: at('08:00'),
    offsetMinutes: 0,
    label: 'Morning Shift Initialized',
    category: 'system',
    severity: 'info',
    source: 'MES',
    recordId: 'shift:MS-2408-01',
    stageId: 'stage-startup',
    graphNodeIds: ['node_production'],
    evidenceIds: ['ev_mes_throughput'],
    confidence: 1,
    value: 'Nominal 10.2 ton/day output',
    description: 'Foundry Line 2 initialized ductile iron casting cycle. Initial baseline SEC recorded at 9.8 kWh/ton.',
    secImpact: 'Baseline: 9.8 kWh/ton',
  },
  {
    id: 'evt_eng_02',
    timestamp: at('08:12'),
    offsetMinutes: 12,
    label: 'Acoustic Leak Frequency Flagged',
    category: 'pneumatic',
    severity: 'warning',
    source: 'Acoustic IoT Sensor',
    recordId: 'sensor:US-AIR-02',
    stageId: 'stage-pneumatic-drift',
    graphNodeIds: ['node_leakage'],
    evidenceIds: ['ev_acoustic_sensor'],
    confidence: 0.91,
    value: '38.4 kHz high-frequency hiss detected',
    description: 'Ultrasonic sensor on Line 2 pneumatic distribution detected turbulent air emission consistent with flexible hose seam rupture.',
    secImpact: 'Pneumatic loss initiating',
  },
  {
    id: 'evt_eng_03',
    timestamp: at('08:18'),
    offsetMinutes: 18,
    label: 'Distribution Header Pressure Drop',
    category: 'sensor',
    severity: 'critical',
    source: 'Pressure Transmitter PT-204',
    recordId: 'scada:PT-204',
    stageId: 'stage-pressure-drop',
    graphNodeIds: ['node_pressure'],
    evidenceIds: ['ev_pressure_telemetry'],
    confidence: 0.98,
    value: '6.1 bar (nominal: 7.2 bar)',
    description: 'Header pressure decreased by 15.3% below operational setpoint, triggering automatic compressor load compensation.',
    secImpact: 'Pressure: -1.1 bar',
  },
  {
    id: 'evt_eng_04',
    timestamp: at('08:24'),
    offsetMinutes: 24,
    label: 'Compressor Modulation & Overcycling',
    category: 'energy',
    severity: 'critical',
    source: 'Compressor SCADA',
    recordId: 'scada:COMP-02',
    stageId: 'stage-compressor-surge',
    graphNodeIds: ['node_compressor_load', 'node_motor_draw'],
    evidenceIds: ['ev_compressor_telemetry'],
    confidence: 0.96,
    value: 'Runtime 88% (+21%) · 142 A (+12%)',
    description: '75 kW main screw compressor forced into continuous on-load modulation to maintain delivery pressure, consuming 18 kW excess power.',
    secImpact: '+18 kW excess draw',
  },
  {
    id: 'evt_eng_05',
    timestamp: at('08:30'),
    offsetMinutes: 30,
    label: 'SEC Anomaly Detected (Threshold Breach)',
    category: 'energy',
    severity: 'critical',
    source: 'Energy Submetering System',
    recordId: 'meter:MTR-LINE2',
    stageId: 'stage-sec-spike',
    graphNodeIds: ['node_sec'],
    evidenceIds: ['ev_sec_calculation'],
    confidence: 0.99,
    value: '11.2 kWh/ton (+14.3% vs yesterday)',
    description: 'ForgeOps Energy detected a sustained 14.3% spike in Specific Energy Consumption while casting throughput (10.2 ton) and quality (97.6%) were unchanged.',
    secImpact: 'SEC Spike: 11.2 kWh/ton',
  },
  {
    id: 'evt_eng_06',
    timestamp: at('08:31'),
    offsetMinutes: 31,
    label: 'Planner Agent Formulates Strategy',
    category: 'system',
    severity: 'info',
    source: 'Planner Agent',
    recordId: 'agent:planner-run-44',
    stageId: 'stage-agentic-investigation',
    graphNodeIds: ['node_sec', 'node_production', 'node_quality'],
    evidenceIds: ['ev_planner_objective'],
    confidence: 1.0,
    value: 'min(SEC) subject to Throughput >= 10.2t, Quality >= 97.6%',
    description: 'Formulated constrained investigation plan. Selected MCP tools across energy meters, SCADA, CMMS maintenance history, and MES production.',
    secImpact: 'Objective initialized',
  },
  {
    id: 'evt_eng_07',
    timestamp: at('08:32'),
    offsetMinutes: 32,
    label: 'Research Agent Collects Evidence Bundle',
    category: 'system',
    severity: 'info',
    source: 'Research Agent',
    recordId: 'agent:research-bundle-12',
    stageId: 'stage-agentic-investigation',
    graphNodeIds: ['node_pressure', 'node_leakage'],
    evidenceIds: ['ev_cmms_leakage_history', 'ev_pressure_telemetry'],
    confidence: 0.95,
    value: '3 leakage incidents logged in last 15 days',
    description: 'Retrieved CMMS maintenance logs showing repetitive temporary patch repairs on Line 2 distribution manifold without fitting replacement.',
    secImpact: 'Historical correlation established',
  },
  {
    id: 'evt_eng_08',
    timestamp: at('08:33'),
    offsetMinutes: 33,
    label: 'Analysis Agent Proves Root Cause',
    category: 'system',
    severity: 'info',
    source: 'Analysis Agent',
    recordId: 'agent:analysis-causal-08',
    stageId: 'stage-agentic-investigation',
    graphNodeIds: ['node_leakage', 'node_pressure', 'node_compressor_load', 'node_sec'],
    evidenceIds: ['ev_root_cause_analysis'],
    confidence: 0.93,
    value: 'Line 2 Compressed-Air Leakage (93% confidence)',
    description: 'Causal inference graph confirmed: Leakage -> Pressure Drop (-1.1 bar) -> Compressor Load (+21%) -> Motor Draw (+12%) -> SEC Surge (+14.3%).',
    secImpact: 'Root cause verified',
  },
  {
    id: 'evt_eng_09',
    timestamp: at('08:35'),
    offsetMinutes: 35,
    label: 'Execution Agent Simulates & Recommends',
    category: 'system',
    severity: 'info',
    source: 'Execution Agent',
    recordId: 'agent:execution-opt-04',
    stageId: 'stage-agentic-investigation',
    graphNodeIds: ['node_sec'],
    evidenceIds: ['ev_simulation_matrix'],
    confidence: 0.94,
    value: 'Option C: Repair + Setpoint (SEC -18.0%, ₹6,240/day savings)',
    description: 'Simulated 4 interventions. Evaluated tradeoff of leakage repair + setpoint reduction to 6.5 bar. Calculated 1.5 month payback and 96 kg CO2/day reduction.',
    secImpact: 'Optimum: 9.2 kWh/ton (-18%)',
  },
  {
    id: 'evt_eng_10',
    timestamp: at('10:15'),
    offsetMinutes: 135,
    label: 'Operator VK Approves Recommendation',
    category: 'operator',
    severity: 'info',
    source: 'Human Approval Gate',
    recordId: 'approval:VK-8821',
    stageId: 'stage-implementation',
    graphNodeIds: ['node_leakage'],
    evidenceIds: ['ev_work_order_dispatch'],
    confidence: 1.0,
    value: 'Work order WO-ENG-8821 dispatched to CMMS',
    description: 'Plant supervisor approved scheduled 48-minute maintenance intervention during die changeover window. Zero unplanned downtime incurred.',
    secImpact: 'Execution authorized',
  },
  {
    id: 'evt_eng_11',
    timestamp: at('11:30'),
    offsetMinutes: 210,
    label: 'Post-Action Verification & Impact Closure',
    category: 'energy',
    severity: 'info',
    source: 'ForgeOps Verification Engine',
    recordId: 'verify:VRF-2408-01',
    stageId: 'stage-verified',
    graphNodeIds: ['node_sec', 'node_production', 'node_quality'],
    evidenceIds: ['ev_verified_impact'],
    confidence: 0.99,
    value: 'SEC: 9.2 kWh/ton (-18.0%) · Throughput: 10.2t · Quality: 97.8%',
    description: 'Air pressure restored to optimal 6.5 bar. Compressor runtime dropped back to 64%. Actual verified savings: 1,840 kWh/day (₹6,240/day). Case closed.',
    secImpact: 'Verified SEC: 9.2 kWh/ton',
  },
];

export const replayStages: ReplayStage[] = [
  {
    id: 'stage-startup',
    label: '08:00 AM — Nominal Shift Start',
    shortLabel: 'Nominal',
    status: 'ok',
    startMinute: 0,
    endMinute: 15,
    summary: 'Line 2 initialized ductile iron batch. Baseline SEC at 9.8 kWh/ton with 7.2 bar pneumatic header pressure.',
    inputs: ['Certified Pig Iron & Scrap', 'Grid Power (HT-2)', 'Pneumatic Header 7.2 bar'],
    outputs: ['Moulding Line Ready', 'Nominal Induction Melt Cycle'],
    metrics: [
      { label: 'Specific Energy (SEC)', value: '9.8 kWh/ton', state: 'normal' },
      { label: 'Header Pressure', value: '7.2 bar', state: 'normal' },
      { label: 'Compressor Runtime', value: '67%', state: 'normal' },
    ],
    eventIds: ['evt_eng_01'],
  },
  {
    id: 'stage-pressure-drop',
    label: '08:18 AM — Pneumatic Pressure Drop',
    shortLabel: 'Pressure Drop',
    status: 'warning',
    startMinute: 15,
    endMinute: 25,
    summary: 'Acoustic leak on Line 2 flexible manifold caused air pressure to plunge to 6.1 bar (-15.3%).',
    inputs: ['Line 2 Pneumatic Tools', 'Ultrasonic Acoustic Sensor'],
    outputs: ['Pressure Drop Alarm', 'Modulation Valve Opening'],
    metrics: [
      { label: 'Air Pressure', value: '6.1 bar', state: 'warning' },
      { label: 'Acoustic Emission', value: '38.4 kHz', state: 'warning' },
      { label: 'Flow Rate', value: '14.2 m³/min', state: 'warning' },
    ],
    eventIds: ['evt_eng_02', 'evt_eng_03'],
  },
  {
    id: 'stage-compressor-surge',
    label: '08:24 AM — Compressor Overcycling',
    shortLabel: 'Compressor Surge',
    status: 'failure',
    startMinute: 25,
    endMinute: 30,
    summary: 'Main screw compressor modulated to 94% capacity, motor current spiked to 142A (+12%), consuming 18 kW excess power.',
    inputs: ['75 kW Screw Compressor', 'Modulation Valve Control'],
    outputs: ['Excess Power Draw', 'Rapid Cycling Heat Build-up'],
    metrics: [
      { label: 'Compressor Runtime', value: '88% (+21%)', state: 'critical' },
      { label: 'Motor Current', value: '142 A (+12%)', state: 'critical' },
      { label: 'Active Power', value: '71.4 kW', state: 'critical' },
    ],
    eventIds: ['evt_eng_04'],
  },
  {
    id: 'stage-sec-spike',
    label: '08:30 AM — SEC Spike (+14.3%)',
    shortLabel: 'SEC Anomaly',
    status: 'failure',
    startMinute: 30,
    endMinute: 40,
    summary: 'Energy submeter flagged SEC surge to 11.2 kWh/ton. Production throughput (10.2t) and quality (97.6%) remained unchanged.',
    inputs: ['Submeter Energy Records', 'MES Batch Weight Scales'],
    outputs: ['ForgeOps Anomaly Trigger', '4-Agent Pipeline Dispatch'],
    metrics: [
      { label: 'SEC (Today)', value: '11.2 kWh/ton', state: 'critical' },
      { label: 'SEC (Yesterday)', value: '9.8 kWh/ton', state: 'normal' },
      { label: 'SEC Delta', value: '+14.3%', state: 'critical' },
      { label: 'Throughput', value: '10.2 ton/day', state: 'normal' },
    ],
    eventIds: ['evt_eng_05', 'evt_eng_06', 'evt_eng_07', 'evt_eng_08', 'evt_eng_09'],
  },
  {
    id: 'stage-verified',
    label: '11:30 AM — Action Verified & Resolved',
    shortLabel: 'Verified Impact',
    status: 'ok',
    startMinute: 135,
    endMinute: 210,
    summary: 'Pneumatic fitting repaired; compressor setpoint optimized to 6.5 bar. SEC dropped to 9.2 kWh/ton (-18.0%). Throughput & quality preserved.',
    inputs: ['CMMS Work Order WO-ENG-8821', 'Pressure Calibrator'],
    outputs: ['SEC Restoration', 'Verified 1,840 kWh/day Saving'],
    metrics: [
      { label: 'Verified SEC', value: '9.2 kWh/ton (-18%)', state: 'normal' },
      { label: 'Daily Savings', value: '₹6,240 / day', state: 'normal' },
      { label: 'CO2 Reduction', value: '96 kg / day', state: 'normal' },
      { label: 'Quality Yield', value: '97.8% (+0.2%)', state: 'normal' },
    ],
    eventIds: ['evt_eng_10', 'evt_eng_11'],
  },
];

export const graphNodes: GraphNode[] = [
  {
    id: 'node_leakage',
    label: 'Line 2 Pneumatic Distribution Leakage',
    type: 'equipment',
    influence: 0.94,
    confidence: 0.93,
    evidenceType: 'observed_correlation',
    controllable: true,
    source: 'Acoustic IoT + CMMS Logs',
    value: 'Acoustic emission 38.4 kHz at manifold coupling',
    threshold: '< 20 kHz baseline',
    description: '3 recurring micro-leak incidents on Line 2 flexible coupling in last 15 days.',
    eventIds: ['evt_eng_02', 'evt_eng_07'],
    evidenceIds: ['ev_acoustic_sensor', 'ev_cmms_leakage_history'],
    position: { x: 80, y: 120 },
  },
  {
    id: 'node_pressure',
    label: 'Distribution Header Pressure Drop',
    type: 'condition',
    influence: 0.91,
    confidence: 0.98,
    evidenceType: 'observed_correlation',
    controllable: true,
    source: 'Pressure Transmitter PT-204',
    value: '6.1 bar (nominal 7.2 bar, -15.3%)',
    threshold: '6.8 - 7.5 bar',
    description: 'Header pressure collapsed below minimum pneumatic actuator operating threshold.',
    eventIds: ['evt_eng_03'],
    evidenceIds: ['ev_pressure_telemetry'],
    position: { x: 280, y: 120 },
  },
  {
    id: 'node_compressor_load',
    label: 'Compressor Modulation Surge (+21% runtime)',
    type: 'process',
    influence: 0.89,
    confidence: 0.96,
    evidenceType: 'observed_correlation',
    controllable: true,
    source: 'Compressor SCADA',
    value: '88% on-load runtime (baseline 67%)',
    threshold: '< 70% nominal',
    description: '75 kW main compressor forced into continuous loaded modulation to compensate for continuous leak.',
    eventIds: ['evt_eng_04'],
    evidenceIds: ['ev_compressor_telemetry'],
    position: { x: 480, y: 120 },
  },
  {
    id: 'node_motor_draw',
    label: 'Motor Current Overdraw (+12%)',
    type: 'condition',
    influence: 0.86,
    confidence: 0.95,
    evidenceType: 'observed_correlation',
    controllable: false,
    source: 'Submeter CT-COMP2',
    value: '142 A (baseline 127 A)',
    threshold: '< 130 A',
    description: 'High-current draw on main compressor motor causing thermal heating and active kWh surge.',
    eventIds: ['evt_eng_04'],
    evidenceIds: ['ev_compressor_telemetry'],
    position: { x: 680, y: 120 },
  },
  {
    id: 'node_sec',
    label: 'Specific Energy Consumption Spike (11.2 kWh/ton)',
    type: 'energy',
    influence: 1.0,
    confidence: 0.99,
    evidenceType: 'counterfactual_simulated',
    controllable: false,
    source: 'Energy Intelligence Engine',
    value: '11.2 kWh/ton (+14.3% vs yesterday)',
    threshold: '< 9.8 kWh/ton target',
    description: 'Energy consumed per ton of good castings increased by 14.3% due entirely to compressed-air losses.',
    eventIds: ['evt_eng_05', 'evt_eng_11'],
    evidenceIds: ['ev_sec_calculation', 'ev_verified_impact'],
    position: { x: 880, y: 120 },
  },
  {
    id: 'node_production',
    label: 'Foundry Daily Throughput (10.2 ton)',
    type: 'outcome',
    influence: 0.12,
    confidence: 0.99,
    evidenceType: 'observed_correlation',
    controllable: false,
    source: 'MES Scale Records',
    value: '10.2 ton/day (0% impact / Preserved)',
    threshold: '>= 10.0 ton/day baseline',
    description: 'Throughput remained completely stable, proving that the energy spike was purely waste rather than increased production.',
    eventIds: ['evt_eng_01', 'evt_eng_05'],
    evidenceIds: ['ev_mes_throughput'],
    position: { x: 680, y: 260 },
  },
  {
    id: 'node_quality',
    label: 'Casting Yield & Quality (97.6%)',
    type: 'outcome',
    influence: 0.08,
    confidence: 0.98,
    evidenceType: 'observed_correlation',
    controllable: false,
    source: 'Quality Inspection System',
    value: '97.6% good casting yield (Preserved)',
    threshold: '>= 97.0% target',
    description: 'Rejection rates unchanged. Defect analysis confirmed no core shrinkage or dimensional drift occurred.',
    eventIds: ['evt_eng_05', 'evt_eng_11'],
    evidenceIds: ['ev_quality_records'],
    position: { x: 480, y: 260 },
  },
];

export const graphEdges: GraphEdge[] = [
  {
    id: 'edge_leak_to_pressure',
    from: 'node_leakage',
    to: 'node_pressure',
    strength: 0.95,
    evidenceType: 'observed_correlation',
    label: 'causes -1.1 bar drop',
  },
  {
    id: 'edge_pressure_to_compressor',
    from: 'node_pressure',
    to: 'node_compressor_load',
    strength: 0.92,
    evidenceType: 'observed_correlation',
    label: 'triggers +21% runtime',
  },
  {
    id: 'edge_compressor_to_motor',
    from: 'node_compressor_load',
    to: 'node_motor_draw',
    strength: 0.94,
    evidenceType: 'observed_correlation',
    label: 'draws +12% current (142A)',
  },
  {
    id: 'edge_motor_to_sec',
    from: 'node_motor_draw',
    to: 'node_sec',
    strength: 0.97,
    evidenceType: 'observed_correlation',
    label: 'spikes SEC to 11.2 kWh/t',
  },
  {
    id: 'edge_production_to_sec',
    from: 'node_production',
    to: 'node_sec',
    strength: 0.15,
    evidenceType: 'observed_correlation',
    label: 'throughput preserved (0% delta)',
  },
  {
    id: 'edge_quality_to_sec',
    from: 'node_quality',
    to: 'node_sec',
    strength: 0.10,
    evidenceType: 'observed_correlation',
    label: 'quality preserved (0% delta)',
  },
];

export const evidenceRecords: EvidenceRecord[] = [
  {
    id: 'ev_sec_calculation',
    title: 'Specific Energy Consumption Telemetry Spike',
    source: 'Energy MCP / Smart Meter MTR-LINE2',
    recordId: 'sec:20260824-0830',
    timestamp: at('08:30'),
    kind: 'energy_telemetry',
    summary: 'Specific energy consumption increased from 9.8 kWh/ton to 11.2 kWh/ton (+14.3%) while throughput remained unchanged at 10.2 ton/day.',
    confidence: 0.99,
    evidenceType: 'observed_correlation',
    metricDetails: {
      metric: 'Specific Energy Consumption (SEC)',
      baseline: '9.8 kWh/ton',
      observed: '11.2 kWh/ton',
      deviation: '+14.3% (+1.4 kWh/ton)',
    },
  },
  {
    id: 'ev_pressure_telemetry',
    title: 'Pneumatic Header Pressure Transmitter Log',
    source: 'Industrial Edge Gateway / Modbus RTU',
    recordId: 'scada:PT-204-LOG',
    timestamp: at('08:18'),
    kind: 'sensor',
    summary: 'Line 2 header pressure dropped from nominal 7.2 bar to 6.1 bar. Pressure drop correlated with pneumatic leak at moulding station 3.',
    confidence: 0.98,
    evidenceType: 'observed_correlation',
    metricDetails: {
      metric: 'Header Delivery Pressure',
      baseline: '7.2 bar',
      observed: '6.1 bar',
      deviation: '-1.1 bar (-15.3%)',
    },
  },
  {
    id: 'ev_compressor_telemetry',
    title: 'Main Screw Compressor Load & Power Telemetry',
    source: 'Compressor Controller / OPC UA',
    recordId: 'scada:COMP-02-METRICS',
    timestamp: at('08:24'),
    kind: 'scada',
    summary: 'Compressor on-load modulation jumped from 67% to 88% (+21%). Active electrical current surged from 127A to 142A (+12%), creating 18 kW parasitic load.',
    confidence: 0.96,
    evidenceType: 'observed_correlation',
    metricDetails: {
      metric: 'Compressor On-Load Runtime',
      baseline: '67%',
      observed: '88%',
      deviation: '+21% runtime (+18 kW)',
    },
  },
  {
    id: 'ev_cmms_leakage_history',
    title: 'CMMS Maintenance Work Order & Leakage History',
    source: 'ForgeOps MCP / CMMS Connector',
    recordId: 'cmms:LOG-LINE2-AIR',
    timestamp: at('08:32'),
    kind: 'record',
    summary: 'Found 3 repetitive maintenance work orders for air leakage on Line 2 distribution manifold in the past 15 days; all were temporary hose clamps.',
    confidence: 0.94,
    evidenceType: 'observed_correlation',
    metricDetails: {
      metric: '15-Day Leak Incidents',
      baseline: '0 incidents',
      observed: '3 temporary repairs',
      deviation: 'Unresolved root wear',
    },
  },
  {
    id: 'ev_mes_throughput',
    title: 'MES Batch Production Output Verification',
    source: 'MES / Weigh Scale Ingestion',
    recordId: 'mes:BATCH-FD-2408',
    timestamp: at('08:30'),
    kind: 'record',
    summary: 'Daily foundry throughput confirmed at 10.2 tons good castings. Verified that SEC spike is pure energy waste, not output growth.',
    confidence: 0.99,
    evidenceType: 'observed_correlation',
    metricDetails: {
      metric: 'Good Production Output',
      baseline: '10.2 ton/day',
      observed: '10.2 ton/day',
      deviation: '0% (Preserved)',
    },
  },
  {
    id: 'ev_quality_records',
    title: 'Final Dimensional & Metallurgical Quality Report',
    source: 'Quality Management System',
    recordId: 'qual:QC-FD-2408',
    timestamp: at('08:30'),
    kind: 'record',
    summary: 'Casting yield at 97.6% (target >= 97.0%). Ultrasonic porosity and tensile strength testing conform to Grade 400/18 specifications.',
    confidence: 0.98,
    evidenceType: 'observed_correlation',
    metricDetails: {
      metric: 'Quality Yield Rate',
      baseline: '97.6%',
      observed: '97.6%',
      deviation: '0% (Preserved)',
    },
  },
  {
    id: 'ev_verified_impact',
    title: 'Post-Intervention Verified Energy Measurement',
    source: 'ForgeOps Verification Engine / Smart Meter',
    recordId: 'verify:VRF-2408-01',
    timestamp: at('11:30'),
    kind: 'comparison',
    summary: 'Post-intervention telemetry proves SEC dropped to 9.2 kWh/ton (-18.0%). Daily savings verified at 1,840 kWh/day (₹6,240/day) with zero throughput loss.',
    confidence: 0.99,
    evidenceType: 'model_estimated',
    metricDetails: {
      metric: 'Post-Action SEC',
      baseline: '11.2 kWh/ton',
      observed: '9.2 kWh/ton',
      deviation: '-18.0% (-2.0 kWh/ton)',
    },
  },
];

export const simulationPresets: Record<string, SimulationResult> = {
  repair_leakage: {
    scenarioId: 'repair_leakage',
    scenarioName: 'Intervention A: Repair Distribution Leakage',
    baselineYield: 97.6,
    predictedYield: 97.6,
    baselineSec: 11.2,
    predictedSec: 9.7,
    secUnit: 'kWh/ton',
    secReductionPct: 13.4,
    energySavingKwhDay: 1370,
    costSavingInrDay: 4650,
    co2ReductionKgDay: 71,
    confidence: 0.95,
    cost: '₹8,500',
    costInr: 8500,
    effort: '42 min maintenance window',
    downtimeMinutes: 42,
    paybackMonths: 1.8,
    throughputImpact: '0% impact (Preserved)',
    qualityImpact: '0% impact (Preserved)',
    safetyPreserved: true,
    assumptions: [
      'Replace cracked flexible coupling on Line 2 with reinforced braided stainless assembly',
      'Execution scheduled during planned shift changeover to prevent throughput disruption',
      'Industrial power tariff calculated at ₹7.8 / kWh',
    ],
    reasoning: 'Eliminating the 14.2 m³/min air leak allows compressor modulation to drop by 16%, saving 1,370 kWh daily with 1.8 month payback.',
    inValidatedRange: true,
    warnings: [],
    evidenceRefs: ['ev_sec_calculation', 'ev_pressure_telemetry', 'ev_cmms_leakage_history'],
    modelVersion: 'ForgeOps-Energy-Sim-v2.4',
  },
  optimize_setpoint: {
    scenarioId: 'optimize_setpoint',
    scenarioName: 'Intervention B: Optimize Compressor Setpoint',
    baselineYield: 97.6,
    predictedYield: 97.6,
    baselineSec: 11.2,
    predictedSec: 10.1,
    secUnit: 'kWh/ton',
    secReductionPct: 9.8,
    energySavingKwhDay: 1000,
    costSavingInrDay: 3400,
    co2ReductionKgDay: 52,
    confidence: 0.92,
    cost: '₹2,000',
    costInr: 2000,
    effort: '10 min controller recalibration',
    downtimeMinutes: 10,
    paybackMonths: 0.6,
    throughputImpact: '0% impact (Preserved)',
    qualityImpact: '0% impact (Preserved)',
    safetyPreserved: true,
    assumptions: [
      'Reduce compressor discharge setpoint from 7.2 bar to optimized 6.5 bar',
      'Verify minimum 5.8 bar at furthest pneumatic moulding cylinder',
      'No hardware replacement required; parameter adjustment only',
    ],
    reasoning: 'Every 0.5 bar pressure reduction delivers approximately 3.5% energy savings on screw compressors. Reduces unloaded modulation draw.',
    inValidatedRange: true,
    warnings: [],
    evidenceRefs: ['ev_compressor_telemetry', 'ev_pressure_telemetry'],
    modelVersion: 'ForgeOps-Energy-Sim-v2.4',
  },
  both_repair_and_optimize: {
    scenarioId: 'both_repair_and_optimize',
    scenarioName: 'Intervention C: Both A + B (Recommended Optimal)',
    baselineYield: 97.6,
    predictedYield: 97.8,
    baselineSec: 11.2,
    predictedSec: 9.2,
    secUnit: 'kWh/ton',
    secReductionPct: 18.0,
    energySavingKwhDay: 1840,
    costSavingInrDay: 6240,
    co2ReductionKgDay: 96,
    confidence: 0.94,
    cost: '₹9,500',
    costInr: 9500,
    effort: '48 min maintenance window',
    downtimeMinutes: 48,
    paybackMonths: 1.5,
    throughputImpact: '0% impact (10.2 ton/day Preserved)',
    qualityImpact: '+0.2% yield improvement (97.8%)',
    safetyPreserved: true,
    assumptions: [
      'Comprehensive repair of Line 2 manifold followed by system recalibration to 6.5 bar',
      'Total intervention completed in 48 minutes during die cleanout',
      'Delivers compound efficiency: lower leakage velocity + reduced compressor work per cycle',
    ],
    reasoning: 'Optimal economic intervention. Combining hardware leak elimination with 6.5 bar operating setpoint delivers 18.0% SEC reduction (1,840 kWh/day) with 1.5 months payback and zero throughput penalty.',
    inValidatedRange: true,
    warnings: [],
    evidenceRefs: ['ev_sec_calculation', 'ev_pressure_telemetry', 'ev_compressor_telemetry', 'ev_cmms_leakage_history'],
    modelVersion: 'ForgeOps-Energy-Sim-v2.4',
  },
  no_action: {
    scenarioId: 'no_action',
    scenarioName: 'Intervention D: No Action (Status Quo)',
    baselineYield: 97.6,
    predictedYield: 97.6,
    baselineSec: 11.2,
    predictedSec: 11.2,
    secUnit: 'kWh/ton',
    secReductionPct: 0.0,
    energySavingKwhDay: 0,
    costSavingInrDay: 0,
    co2ReductionKgDay: 0,
    confidence: 0.99,
    cost: '₹0',
    costInr: 0,
    effort: 'None',
    downtimeMinutes: 0,
    paybackMonths: 0,
    throughputImpact: 'High risk of unplanned compressor trip',
    qualityImpact: 'Pneumatic clamp pressure degradation risk',
    safetyPreserved: false,
    assumptions: [
      'Allow leak to continue unaddressed',
      'Ongoing excess electrical billing of ₹1,87,200 per month',
      'Elevated thermal stress on 75 kW compressor motor',
    ],
    reasoning: 'Status quo results in continuous financial waste and high risk of unplanned pneumatic failure during peak melting shifts.',
    inValidatedRange: true,
    warnings: ['Severe risk of compressor motor thermal trip and uncommanded line shutdown.'],
    evidenceRefs: ['ev_sec_calculation'],
    modelVersion: 'ForgeOps-Energy-Sim-v2.4',
  },
};

export const recommendations: Recommendation[] = [
  {
    id: 'rec_eng_01',
    rank: 1,
    title: 'Repair Line 2 compressed-air leakage and optimize compressor setpoint to 6.5 bar',
    confidence: 0.94,
    predictedYield: 97.8,
    predictedSec: 9.2,
    secReductionPct: 18.0,
    energySavingKwhDay: 1840,
    costSavingInrDay: 6240,
    co2ReductionKgDay: 96,
    paybackPeriod: '1.5 months',
    cost: '₹9,500',
    costInr: 9500,
    effort: '48 min maintenance window during planned changeover',
    downtime: '48 min (zero production penalty)',
    impact: 'High',
    risk: 'Low',
    description: 'Replace defective flexible pneumatic coupling on Line 2 distribution manifold with high-pressure braided assembly, and reduce master compressor discharge setpoint from 7.2 bar to 6.5 bar. Delivers 1,840 kWh daily savings (₹6,240/day) with 1.5 months payback.',
    savingsPerWeekInr: 43680,
    savingsPerMonthInr: 187200,
    evidenceRefs: ['ev_sec_calculation', 'ev_pressure_telemetry', 'ev_compressor_telemetry', 'ev_cmms_leakage_history'],
    status: 'pending',
  },
  {
    id: 'rec_eng_02',
    rank: 2,
    title: 'Urgent leakage repair on Line 2 manifold only (Intervention A)',
    confidence: 0.95,
    predictedYield: 97.6,
    predictedSec: 9.7,
    secReductionPct: 13.4,
    energySavingKwhDay: 1370,
    costSavingInrDay: 4650,
    co2ReductionKgDay: 71,
    paybackPeriod: '1.8 months',
    cost: '₹8,500',
    costInr: 8500,
    effort: '42 min mechanical repair',
    downtime: '42 min',
    impact: 'Medium',
    risk: 'Low',
    description: 'Repair the physical pneumatic leak immediately while keeping current 7.2 bar setpoint. Recovers 13.4% SEC without changing operating controls.',
    savingsPerWeekInr: 32550,
    savingsPerMonthInr: 139500,
    evidenceRefs: ['ev_pressure_telemetry', 'ev_cmms_leakage_history'],
    status: 'pending',
  },
  {
    id: 'rec_eng_03',
    rank: 3,
    title: 'Install automatic solenoid shutoff on Line 2 non-operational idle branches',
    confidence: 0.88,
    predictedYield: 97.6,
    predictedSec: 10.4,
    secReductionPct: 7.1,
    energySavingKwhDay: 720,
    costSavingInrDay: 2450,
    co2ReductionKgDay: 37,
    paybackPeriod: '2.8 months',
    cost: '₹18,000',
    costInr: 18000,
    effort: '2 hours weekend retrofit',
    downtime: '0 min (during shutdown)',
    impact: 'Medium',
    risk: 'Low',
    description: 'Retrofit automated PLC-controlled pneumatic isolation valves to isolate inactive moulding banks during pattern changeovers, eliminating off-shift leakage.',
    savingsPerWeekInr: 17150,
    savingsPerMonthInr: 73500,
    evidenceRefs: ['ev_compressor_telemetry'],
    status: 'pending',
  },
];

export const businessImpact: BusinessImpact = {
  currentMonthlyLossInr: 187200,
  monthlySavingsInr: 187200,
  downtimeReductionPct: 0,
  baselineYield: 97.6,
  predictedYield: 97.8,
  baselineSec: 11.2,
  optimizedSec: 9.2,
  secImprovementPct: 18.0,
  dailyKwhSaved: 1840,
  annualCo2ReductionTons: 35.0,
  paybackPeriod: '1.5 months',
  basis: '10.2 ton/day ductile iron casting output at ₹7.8/kWh industrial electricity tariff over 26 working days/month',
};

export const agentTraceSteps = [
  {
    agent: 'planner' as const,
    agentTitle: '1. Planner Agent',
    status: 'complete' as const,
    durationMs: 310,
    model: 'Gemini 3.8 Flash (High Reasoning)',
    objective: 'Define energy optimization objective and operational boundary constraints',
    summary: 'Formulated primary objective: min(SEC = kWh / ton good casting). Set hard constraints: Throughput >= 10.2 ton/day, Quality Yield >= 97.6%, Safety = Preserved. Formulated investigation plan and selected MCP tools: Energy Telemetry, Pneumatics SCADA, CMMS Maintenance History, MES Production.',
    keyOutputs: [
      'Objective: min(SEC) subject to Throughput >= Baseline, Quality >= Baseline, Safety = Preserved',
      'Target line: Induction Melting & Moulding Line 2',
      'Active MCP Tool Suite: [energy_telemetry, scada_pneumatics, cmms_logs, mes_yield]',
    ],
  },
  {
    agent: 'research' as const,
    agentTitle: '2. Research Agent',
    status: 'complete' as const,
    durationMs: 460,
    model: 'Gemini 3.8 Flash (High Reasoning)',
    objective: 'Retrieve multi-domain manufacturing and energy evidence across plant systems',
    summary: 'Queried smart energy meters (MTR-LINE2), pressure transmitter (PT-204), and compressor controller (COMP-02). Correlated CMMS maintenance logs showing 3 recurring flexible hose patch repairs in past 15 days. Verified MES daily output (10.2t) and quality yield (97.6%) were unaffected.',
    keyOutputs: [
      'SEC increased from 9.8 to 11.2 kWh/ton (+14.3%)',
      'Air pressure collapsed from 7.2 to 6.1 bar (-15.3%)',
      'Compressor on-load runtime surged from 67% to 88% (+21%)',
      'Motor current spiked from 127A to 142A (+12%)',
    ],
  },
  {
    agent: 'analysis' as const,
    agentTitle: '3. Analysis Agent',
    status: 'complete' as const,
    durationMs: 540,
    model: 'Gemini 3.8 Flash (High Reasoning)',
    objective: 'Detect anomalies, calculate SEC, establish causal chain and root cause',
    summary: 'Correlated the 1.1 bar pneumatic pressure drop with compressor on-load runtime spike and 18 kW excess electrical draw. Established causal inference: Line 2 Pneumatic Leakage -> Pressure Drop -> Modulation Overcycling -> SEC Surge. Confirmed root cause with 93% confidence.',
    keyOutputs: [
      'Root Cause: Compressed-air distribution leakage on Line 2 manifold (93% confidence)',
      'Energy Waste: 1,840 kWh/day unrecovered parasitic draw',
      'Confirmed: Energy spike is 100% waste (Throughput and Quality unaffected)',
    ],
  },
  {
    agent: 'execution' as const,
    agentTitle: '4. Execution Agent (What-If & Optimization)',
    status: 'complete' as const,
    durationMs: 620,
    model: 'Gemini 3.8 Flash (High Reasoning)',
    objective: 'Run what-if scenario simulations, optimize interventions, quantify ROI and recommend action',
    summary: 'Executed multi-objective optimization across 4 scenarios (A: Leak repair, B: Setpoint optimization, C: Both A+B, D: No action). Tradeoff analysis identified Option C as optimal: SEC drops to 9.2 kWh/ton (-18.0%), saving 1,840 kWh/day (₹6,240/day) with 1.5 months payback and zero production downtime.',
    keyOutputs: [
      'Recommended Action: Repair Line 2 leakage and optimize compressor setpoint to 6.5 bar',
      'Financial ROI: ₹6,240 / day saving (₹1,87,200 / month) · Payback: 1.5 months',
      'Carbon Abatement: 96 kg CO2 / day (28.8 tCO2e / year)',
      'Awaiting human operator approval gate before CMMS dispatch',
    ],
  },
];

export const energyWasteBreakdown: WasteBreakdownItem[] = [
  { category: 'Compressed Air', percentage: 28, kwh: 350, color: '#38bdf8' },
  { category: 'Furnace Thermal', percentage: 26, kwh: 325, color: '#f97316' },
  { category: 'Motors & Drives', percentage: 20, kwh: 250, color: '#10b981' },
  { category: 'Fans & Pumps', percentage: 14, kwh: 175, color: '#a855f7' },
  { category: 'Lighting & HVAC', percentage: 6, kwh: 75, color: '#eab308' },
  { category: 'Others / Auxiliaries', percentage: 6, kwh: 75, color: '#64748b' },
];

export const topAnomalies: AnomalySummary[] = [
  {
    id: 'anom_01',
    title: 'Compressor Header Pressure Drop',
    severity: 'high',
    impactPct: 18,
    description: 'Pneumatic pressure dropped from 7.2 to 6.1 bar; compressor modulation increased by 21%.',
    equipment: 'Line 2 Pneumatics & Screw Compressor COMP-02',
  },
  {
    id: 'anom_02',
    title: 'Motor Overcurrent on Line 2 Drive',
    severity: 'high',
    impactPct: 12,
    description: 'Current sustained at 142A (+12% above nominal 127A); increased thermal loss.',
    equipment: '75 kW Compressor Motor M-2',
  },
  {
    id: 'anom_03',
    title: 'Furnace Temperature Variability',
    severity: 'medium',
    impactPct: 9,
    description: 'Hold-fire cycle power fluctuations during billet charging.',
    equipment: 'Induction Furnace F-1',
  },
  {
    id: 'anom_04',
    title: 'High Idle Energy Draw on Sand Muller',
    severity: 'medium',
    impactPct: 7,
    description: 'Hydraulic pump draws 14% higher idle amperage when muller is empty.',
    equipment: 'Sand Preparation Muller M-5',
  },
];

export const decarbonisationStats = {
  scope1TonsDay: 0.18,
  scope2TonsDay: 0.63,
  totalCo2TonsDay: 0.81,
  baselineCo2TonsDay: 0.90,
  reductionPct: 9.4,
  renewablePct: 18.2,
  renewableTargetPct: 30.0,
  annualSavingsCo2Tons: 35.0,
};

export const assistantResponses: Record<string, AssistantResponse> = {
  default: {
    intent: 'analyze_energy_anomaly',
    conclusion: 'Line 2 Specific Energy Consumption rose by 14.3% due to compressed-air leakage causing severe pressure drop (-1.1 bar) and compressor overcycling (+21% runtime).',
    effect: 'Casting throughput (10.2t) and quality (97.6%) are unaffected, proving the energy surge is 100% addressable waste. Repairing the leak and optimizing setpoint to 6.5 bar reduces SEC by 18.0% (₹6,240/day savings, 1.5 mo payback).',
    confidence: 0.94,
    evidenceRefs: ['ev_sec_calculation', 'ev_pressure_telemetry', 'ev_compressor_telemetry', 'ev_cmms_leakage_history'],
    assumptions: [
      'Line 2 casting throughput remains at 10.2 tons/day baseline',
      'Leakage repair completed during scheduled 48-minute die changeover',
      'Electricity tariff at ₹7.8 / kWh industrial rate',
    ],
    actions: ['open_evidence', 'run_comparison', 'generate_report'],
    toolTrace: [
      { id: 't1', server: 'forgeops-energy-mcp', tool: 'get_energy_telemetry', status: 'complete', durationMs: 140, records: ['meter:MTR-LINE2'] },
      { id: 't2', server: 'forgeops-energy-mcp', tool: 'get_pneumatic_metrics', status: 'complete', durationMs: 110, records: ['scada:PT-204', 'scada:COMP-02'] },
      { id: 't3', server: 'forgeops-energy-mcp', tool: 'get_maintenance_history', status: 'complete', durationMs: 160, records: ['cmms:LOG-LINE2-AIR'] },
      { id: 't4', server: 'forgeops-energy-mcp', tool: 'simulate_energy_intervention', status: 'complete', durationMs: 210, records: ['sim:both_repair_and_optimize'] },
    ],
    agentTrace: agentTraceSteps,
    uiActions: [
      { action: 'HIGHLIGHT_NODE', targetId: 'node_leakage' },
      { action: 'HIGHLIGHT_NODE', targetId: 'node_sec' },
    ],
    generatedReports: [
      {
        reportType: 'BEE Energy Audit & Intervention Brief',
        markdown: `### ForgeOps Energy Executive Decision Brief: Line 2 Foundry SEC Restoration

**Plant:** Foundry Cluster - Belgaum | **Line:** Induction Melting & Moulding Line 2  
**Incident:** INC-ENG-2401 | **Priority:** High  
**Objective:** $\\min \\text{SEC} = \\frac{\\text{kWh}}{\\text{ton good casting}}$

#### 1. Anomaly Diagnosis
At 08:30 AM, ForgeOps Energy detected a **+14.3% surge in Specific Energy Consumption** ($9.8 \\to 11.2\\text{ kWh/ton}$) on Line 2. Total daily electrical draw rose to 8,500 kWh, incurring an excess loss of ₹1,87,200 per month.
Crucially, MES production records confirmed casting throughput was nominal at **10.2 tons/day** and quality yield was **97.6%** (target $\\ge 97.0\\%$). This definitively proved the energy spike was non-productive waste.

#### 2. Root Cause Evidence
- **Pneumatic Pressure Drop:** Pressure transmitter PT-204 recorded a continuous drop from 7.2 bar to 6.1 bar (-15.3%).
- **Compressor Runtime Overcycling:** The 75 kW main screw compressor modulation increased from 67% to 88% on-load (+21% runtime), with motor current surging to 142A (+12%).
- **CMMS Correlation:** Maintenance logs revealed 3 recurring patch repairs on Line 2 flexible coupling in the last 15 days.
- **Probable Root Cause:** Distribution leakage at Line 2 moulding station manifold (93% confidence).

#### 3. What-If Scenario Optimization & Recommendation
ForgeOps Energy simulated 4 interventions:
1. **Intervention A (Repair Leakage):** SEC 9.7 kWh/ton (-13.4%), ₹4,650/day saved, ₹8,500 cost, 42 min downtime.
2. **Intervention B (Optimize Setpoint to 6.5 bar):** SEC 10.1 kWh/ton (-9.8%), ₹3,400/day saved, ₹2,000 cost, 10 min downtime.
3. **Intervention C (Both A + B - RECOMMENDED):** SEC 9.2 kWh/ton (-18.0%), **₹6,240/day saved (1,840 kWh/day)**, 96 kg $\\text{CO}_2$/day reduction, **₹9,500 cost, 1.5 months payback period**.
4. **Intervention D (No Action):** Status quo loss of ₹1.87 Lakhs/month with severe risk of compressor trip.

#### 4. Human Approval Gate
Action requires supervisor approval to dispatch CMMS Work Order WO-ENG-8821 for execution during the upcoming 48-minute die changeover window.
`,
      },
    ],
    notifications: [
      {
        recipient: 'Plant Manager & Energy Auditor',
        subject: '[ACTION REQUIRED] Line 2 SEC Reduction Intervention Approval (₹6,240/day saving)',
        body: 'ForgeOps Energy has isolated the root cause of the +14.3% SEC surge to Line 2 air leakage. Recommended intervention C delivers 18% SEC reduction with 1.5 months payback. Approval requested.',
        requiresApproval: true,
      },
    ],
  },
};
